import type { LicenseRecord, MarketSource, ProductOpportunity, ProductStatus, ProductTestRecord, SalesTestRecord } from "../types/workbench";

const day = 86_400_000;
export function opportunityScore(p: ProductOpportunity) { if (p.ipRisk === "blocked" || p.complianceRisk === "blocked" || p.licenseStatus === "personal-use-only") return 0; const base = p.demandScore * .2 + p.profitScore * .2 + p.shippingScore * .15 + p.customizationScore * .15 + (100 - p.competitionScore) * .1 + p.videoScore * .1 + p.repeatabilityScore * .1; const penalty = (p.ipRisk === "medium" ? 10 : p.ipRisk === "high" ? 30 : 0) + (p.complianceRisk === "medium" ? 10 : p.complianceRisk === "high" ? 25 : 0) + (p.licenseStatus === "unknown" ? 15 : 0); return Math.round(Math.max(0, Math.min(100, base - penalty))); }
export function evidenceInfo(sources: MarketSource[], now = Date.now()) { const stale = sources.filter((x) => now - Date.parse(x.checkedAt) > 30 * day); const score = sources.length ? Math.round(sources.reduce((sum, x) => sum + (x.confidence === "high" ? 100 : x.confidence === "medium" ? 65 : 35), 0) / sources.length) : 0; return { count: sources.length, score, stale: stale.length, lastReviewed: [...sources].sort((a,b) => b.checkedAt.localeCompare(a.checkedAt))[0]?.checkedAt }; }
export function profit(p: ProductOpportunity) { const c=p.costSettings??{}; const price=p.sellingPriceCad??0; const material=p.materialCostCad??0; const direct=material+(c.supportMaterialCostCad??0)+(p.packagingCostCad??0)+(p.shippingCostCad??0)+(c.electricityCostCad??0)+(c.paintFinishingCostCad??0)+(c.returnLossAllowanceCad??0); const operating=(p.printTimeHours??0)*(c.depreciationPerHourCad??0)+(c.manualLaborMinutes??0)/60*(c.laborHourlyCad??0); const fees=price*((c.platformFeePercent??0)+(c.paymentFeePercent??0)+(c.advertisingPercent??0))/100+(c.listingFeeCad??0)+(c.advertisingCostCad??0); const failure=(direct+operating)*(c.failureLossPercent??0)/100; const total=direct+operating+fees+failure; const net=price-total; return { direct, fees, operating, total, gross:price-direct, net, grossMargin:price? (price-direct)/price*100:0, netMargin:price?net/price*100:0, netPerMachineHour:(p.printTimeHours??0)?net/(p.printTimeHours??0):0, netPerLaborHour:(c.manualLaborMinutes??0)?net/((c.manualLaborMinutes??0)/60):0 }; }
export function salesMetrics(x: SalesTestRecord) { const ratio=(n?:number,d?:number)=>d&&d>0?((n??0)/d*100):0; return { ctr:ratio(x.views,x.impressions), favoriteRate:ratio(x.favorites,x.views), inquiryRate:ratio(x.inquiries,x.views), conversionRate:ratio(x.orders,x.views), returnRate:ratio(x.returns,x.orders), revenue:x.revenueCad??(x.orders??0)*(x.testPriceCad??0) }; }
export function salesDiagnosis(x?: SalesTestRecord) { if(!x || !(x.impressions||x.views||x.orders)) return "暂无有效销售数据：继续小范围测试并记录曝光、点击和订单。"; const m=salesMetrics(x); if((x.impressions??0)>=100 && m.ctr<1) return "曝光较高但点击低：优先检查标题、主图和首屏卖点。"; if((x.views??0)>=20 && m.conversionRate<1) return "点击后下单低：检查价格、运费、信任信息和商品页说明。"; if((x.orders??0)>0 && m.returnRate>8) return "已有订单但退货率偏高：检查质量、尺寸说明与预期管理。"; if((x.impressions??0)<100 && m.conversionRate>=3) return "转化表现不错但流量不足：产品有效，优先补充曝光。"; return "数据正在积累：继续测试并在下一周期复盘。"; }
export function approvalMissing(p: ProductOpportunity, tests: ProductTestRecord[], sales: SalesTestRecord[], licenses: LicenseRecord[]) { const missing:string[]=[]; const licenseOk=["original","commercial-license"].includes(p.licenseStatus) && !!(p.licenseEvidence || licenses.some((x)=>x.productId===p.id && x.proofOfLicense)); if(!licenseOk) missing.push("有效的商业许可与可核验证据"); if(["high","blocked"].includes(p.ipRisk)) missing.push("IP 风险需降至中低"); if(["high","blocked"].includes(p.complianceRisk)) missing.push("合规风险需降至中低"); if(!tests.some((x)=>x.productId===p.id && x.result==="pass")) missing.push("至少一条通过的打印测试"); if(!(p.sellingPriceCad && p.materialCostCad!==undefined && p.printTimeHours!==undefined)) missing.push("售价、材料成本与打印时长"); if(!sales.some((x)=>x.productId===p.id && ((x.impressions??0)>0 || (x.views??0)>0 || (x.orders??0)>0))) missing.push("至少一条有效销售测试"); return missing; }
export function transitionProduct(p: ProductOpportunity, target: ProductStatus, tests: ProductTestRecord[], sales: SalesTestRecord[], licenses: LicenseRecord[]) { if(target==="approved") { const missing=approvalMissing(p,tests,sales,licenses); if(missing.length) return { ok:false as const, message:`无法批准：还缺少${missing.join("、")}。`}; } if(target==="test-selling" && !tests.some((x)=>x.productId===p.id&&x.result==="pass")) return { ok:false as const,message:"无法进入销售测试：请先记录至少一条通过的打印测试。"}; return {ok:true as const}; }
