const GENERIC = new Set(["3d", "print", "printable", "model", "stl", "file", "design", "object", "the", "and", "for", "with"]);
export function normalizeText(value = "") { return value.toLowerCase().normalize("NFKC").replace(/[^\p{L}\p{N}]+/gu, " ").trim(); }
export function tokens(value = "") { return [...new Set(normalizeText(value).split(/\s+/).filter((token) => token.length > 1 && !GENERIC.has(token)))]; }
export function canonicalUrl(value = "") { try { const url = new URL(value); url.hash = ""; [...url.searchParams.keys()].forEach((key) => { if (/^(utm_|ref|source|campaign|tracking|fbclid|gclid)/i.test(key)) url.searchParams.delete(key); }); url.hostname = url.hostname.toLowerCase().replace(/^www\./, ""); return url.toString().replace(/\/$/, ""); } catch { return ""; } }
export function overlap(left = [], right = []) { if (!left.length || !right.length) return 0; const a = new Set(left), b = new Set(right); const shared = [...a].filter((item) => b.has(item)).length; return shared / Math.max(a.size, b.size); }
export function duplicateScore(raw, item) {
  const rawUrl = canonicalUrl(raw.url); const urls = item.sources?.map((source) => canonicalUrl(source.url)) ?? [];
  if (rawUrl && urls.includes(rawUrl)) return { score: 1, reasons: ["规范化链接相同"] };
  const title = overlap(tokens(raw.title), tokens(item.title)); const keywords = overlap(raw.keywords ?? tokens(raw.title), item.keywords ?? []); const description = overlap(tokens(raw.description), tokens(item.description)); const image = raw.imageUrl && raw.imageUrl === item.imageUrl ? 1 : 0;
  const rawPrice = Number(raw.price); const existingPrice = item.sources?.find((source) => source.price)?.price; const price = rawPrice > 0 && existingPrice > 0 ? Math.max(0, 1 - Math.abs(rawPrice - existingPrice) / Math.max(rawPrice, existingPrice)) : 0;
  const score = title * .5 + keywords * .15 + description * .1 + image * .15 + price * .1;
  return { score, reasons: [[title,"标题"],[keywords,"关键词"],[description,"描述"],[image,"图片"],[price,"价格"]].filter(([value]) => value >= .6).map(([, label]) => `${label}相似`) };
}
export function findDuplicate(raw, items) { let best; for (const item of items) { const result = duplicateScore(raw, item); if (!best || result.score > best.score) best = { item, ...result }; } if (!best || best.score < .6) return undefined; return { ...best, confidence: best.score >= .85 ? "high" : "medium" }; }
export function mergeInto(existing, raw, now) { existing.lastSeenAt = now; existing.sources ??= []; if (!existing.sources.some((source) => canonicalUrl(source.url) === canonicalUrl(raw.url))) existing.sources.push({ platform: raw.source, url: raw.url, externalId: raw.externalId, discoveredAt: now, price: raw.price, currency: raw.currency, views: raw.views, likes: raw.likes, reviews: raw.reviews }); existing.description ||= raw.description; existing.imageUrl ||= raw.imageUrl; existing.images ??= []; if (raw.imageUrl && !existing.images.some((image) => image.url === raw.imageUrl)) existing.images.push({ url: raw.imageUrl, attribution: raw.attribution ?? raw.source, sourceUrl: raw.url, capturedAt: now }); existing.category ||= raw.category; existing.keywords = [...new Set([...(existing.keywords ?? []), ...(raw.keywords ?? [])])]; return existing; }
export function matchModels(item, assets, rejectedIds = [], threshold = 25) { const query = tokens(`${item.title} ${item.category ?? ""} ${(item.keywords ?? []).join(" ")} ${item.description ?? ""}`); return assets.map((asset) => { const candidate = tokens(`${asset.name ?? ""} ${asset.fileName ?? ""} ${asset.folderName ?? ""} ${(asset.tags ?? []).join(" ")} ${asset.category ?? ""} ${asset.description ?? ""}`); const matchedKeywords = query.filter((token) => candidate.includes(token)); return { modelAssetId: asset.id, score: query.length ? Math.round(matchedKeywords.length / query.length * 100) : 0, matchedKeywords }; }).filter((match) => match.score >= threshold && !rejectedIds.includes(match.modelAssetId)).sort((a,b) => b.score - a.score).slice(0,5); }
export function filterItems(items, filters) { return items.filter((item) => (!filters.keyword || normalizeText(`${item.title} ${(item.keywords ?? []).join(" ")}`).includes(normalizeText(filters.keyword))) && (!filters.platform || item.sources?.some((source) => source.platform === filters.platform)) && (!filters.category || item.category === filters.category) && (!filters.recommendation || item.recommendation === filters.recommendation) && (!filters.status || item.status === filters.status) && (!filters.ipRisk || item.ipRisk === filters.ipRisk) && (!filters.hasMatch || (item.matchedModelAssetIds ?? []).length > 0)); }
export function sortItems(items, sort) { const copy = [...items]; const priceProfit = (item) => item.estimatedProfitMax ?? -Infinity; if (sort === "heat") return copy.sort((a,b) => (b.heatScore ?? -1) - (a.heatScore ?? -1)); if (sort === "competition") return copy.sort((a,b) => (a.competitionScore ?? Infinity) - (b.competitionScore ?? Infinity)); if (sort === "profit") return copy.sort((a,b) => priceProfit(b) - priceProfit(a)); if (sort === "oldest") return copy.sort((a,b) => a.firstSeenAt.localeCompare(b.firstSeenAt)); if (sort === "newest") return copy.sort((a,b) => b.firstSeenAt.localeCompare(a.firstSeenAt)); const rank={recommended:3,watch:2,skip:1}; return copy.sort((a,b)=>(rank[b.recommendation]??0)-(rank[a.recommendation]??0)); }
export function conversionDecision(item, products, modelAssetId) { const existing = products.find((product) => product.radarItemId === item.id); if (existing || item.conversionProductId || item.status === "converted") return { action: "existing", productId: existing?.id ?? item.conversionProductId }; if (!modelAssetId) return { action: "design", status: "preparing" }; return { action: "queue", status: "queued", modelAssetId }; }
