import { Link, useParams } from "react-router-dom";
import { ConfirmDelete } from "../components/ui/ConfirmDelete";
import { Field } from "../components/ui/Field";
import { PageHeader } from "../components/ui/PageHeader";
import { ProductVisualComparison } from "../components/product/ProductVisualComparison";
import { useWorkbench } from "../state/WorkbenchProvider";
import { createId } from "../utils/ids";
import { approvalMissing, evidenceInfo, profit, salesDiagnosis, salesMetrics, transitionProduct } from "../utils/productRules";
import type { LicenseRecord, ProductOpportunity, ProductStatus, ProductTestRecord, SalesTestRecord } from "../types/workbench";

function StageActions({ product, onMove }: { product: ProductOpportunity; onMove: (status: ProductStatus) => void }) { return <div className="button-row"><Link className="button ghost" to="/product-radar">返回雷达</Link><button className="button ghost" onClick={() => onMove("test-print")}>进入打印测试</button><button className="button ghost" onClick={() => onMove("test-selling")}>进入销售测试</button><button className="button primary" onClick={() => onMove("approved")}>批准</button><button className="button danger" onClick={() => onMove("rejected")}>拒绝</button></div>; }
function Overview({ product, update }: { product: ProductOpportunity; update: (patch: Partial<ProductOpportunity>) => void }) { const money = profit(product); return <section className="panel form-panel"><h2>基本信息与利润</h2><Field label="名称"><input value={product.name} onChange={e => update({ name: e.target.value })} /></Field><Field label="描述"><textarea value={product.description} onChange={e => update({ description: e.target.value })} /></Field><div className="form-grid">{[["售价 CAD", "sellingPriceCad"], ["材料成本 CAD", "materialCostCad"], ["打印小时", "printTimeHours"]].map(([label, key]) => <Field key={key} label={label}><input type="number" value={product[key as keyof ProductOpportunity] as number ?? ""} onChange={e => update({ [key]: Number(e.target.value) || undefined })} /></Field>)}</div><p>直接成本 CA${money.direct.toFixed(2)} · 估算净利润 CA${money.net.toFixed(2)} · 净利率 {money.netMargin.toFixed(1)}%。估算不保证实际结果。</p></section>; }
function LicenseSection({ product, records }: { product: ProductOpportunity; records: LicenseRecord[] }) { const { dispatch } = useWorkbench(); const record = records[0]; const save = (patch: Partial<LicenseRecord>) => dispatch({ type: "upsertLicenseRecord", record: { ...record, id: record?.id ?? createId("license"), productId: product.id, modelName: product.name, licenseType: product.licenseStatus, ...patch } }); return <section className="panel"><h2>结构化授权</h2>{!record && product.licenseEvidence && <button className="button ghost" onClick={() => save({ proofOfLicense: product.licenseEvidence, platformRestrictions: "由旧授权证据迁移，请确认实体销售许可。" })}>转换旧授权证据为草稿</button>}<div className="form-grid"><Field label="授权类型"><select value={record?.licenseType ?? product.licenseStatus} onChange={e => save({ licenseType: e.target.value as LicenseRecord["licenseType"] })}>{["original","commercial-license","permission-required","personal-use-only","unknown"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="设计师"><input value={record?.designer ?? ""} onChange={e => save({ designer: e.target.value })} /></Field><Field label="平台"><input value={record?.platform ?? ""} onChange={e => save({ platform: e.target.value })} /></Field><Field label="模型 URL"><input value={record?.modelUrl ?? ""} onChange={e => save({ modelUrl: e.target.value })} /></Field><Field label="许可凭据"><input value={record?.proofOfLicense ?? ""} onChange={e => save({ proofOfLicense: e.target.value })} /></Field><Field label="最后复核"><input type="date" value={record?.lastReviewedAt ?? ""} onChange={e => save({ lastReviewedAt: e.target.value })} /></Field></div><div className="tag-row">{[["physicalSalesAllowed","允许实体销售"],["attributionRequired","需要署名"],["activeSubscriptionRequired","需要订阅"]].map(([key,label]) => <label key={key}><input type="checkbox" checked={Boolean(record?.[key as keyof LicenseRecord])} onChange={e => save({ [key]: e.target.checked })} />{label}</label>)}</div><Field label="平台限制"><textarea value={record?.platformRestrictions ?? ""} onChange={e => save({ platformRestrictions: e.target.value })} /></Field>{record && <ConfirmDelete onConfirm={() => dispatch({ type: "deleteLicenseRecord", id: record.id })} />}</section>; }
function PrintTests({ product, records }: { product: ProductOpportunity; records: ProductTestRecord[] }) { const { dispatch } = useWorkbench(); const add=()=>dispatch({type:"upsertProductTestRecord",record:{id:createId("print"),productId:product.id,name:"打印测试",testDate:new Date().toISOString().slice(0,10),successfulQuantity:0,failedQuantity:0,result:"revise",updatedAt:new Date().toISOString()}}); const save=(record:ProductTestRecord,patch:Partial<ProductTestRecord>)=>{const next={...record,...patch}; const total=(next.successfulQuantity??0)+(next.failedQuantity??0); if(total>0) next.printSuccessRate=(next.successfulQuantity??0)/total*100; dispatch({type:"upsertProductTestRecord",record:next});}; return <section className="panel"><h2>打印测试</h2><button className="button ghost" onClick={add}>新增打印测试</button>{records.map(r=><article className="list-card" key={r.id}><div className="form-grid"><input value={r.name??""} onChange={e=>save(r,{name:e.target.value})}/><input type="date" value={r.testDate??""} onChange={e=>save(r,{testDate:e.target.value})}/><input type="number" placeholder="成功数量" value={r.successfulQuantity??0} onChange={e=>save(r,{successfulQuantity:Number(e.target.value)||0})}/><input type="number" placeholder="失败数量" value={r.failedQuantity??0} onChange={e=>save(r,{failedQuantity:Number(e.target.value)||0})}/><input type="number" placeholder="实际打印小时" value={r.printTimeHours??""} onChange={e=>save(r,{printTimeHours:Number(e.target.value)||undefined})}/><select value={r.result??"revise"} onChange={e=>save(r,{result:e.target.value as ProductTestRecord["result"]})}><option value="pass">通过</option><option value="revise">修改</option><option value="fail">失败</option></select></div><p>自动成功率：{(r.printSuccessRate??0).toFixed(1)}%</p><textarea placeholder="缺陷与备注" value={r.notes??""} onChange={e=>save(r,{notes:e.target.value})}/><ConfirmDelete onConfirm={()=>dispatch({type:"deleteProductTestRecord",id:r.id})}/></article>)}</section>; }
function SalesTests({ product, records }: { product: ProductOpportunity; records: SalesTestRecord[] }) { const { dispatch }=useWorkbench(); const add=()=>dispatch({type:"upsertSalesTestRecord",record:{id:createId("sales"),productId:product.id,platform:"Etsy",periodStart:new Date().toISOString().slice(0,10),impressions:0,views:0,updatedAt:new Date().toISOString()}}); const save=(r:SalesTestRecord,p:Partial<SalesTestRecord>)=>dispatch({type:"upsertSalesTestRecord",record:{...r,...p}}); return <section className="panel"><h2>销售测试</h2><button className="button ghost" onClick={add}>新增销售测试</button>{records.map(r=>{const m=salesMetrics(r);return <article className="list-card" key={r.id}><div className="form-grid"><input value={r.platform} onChange={e=>save(r,{platform:e.target.value})}/><input type="date" value={r.periodStart??""} onChange={e=>save(r,{periodStart:e.target.value})}/><input type="date" value={r.periodEnd??""} onChange={e=>save(r,{periodEnd:e.target.value})}/>{["impressions","views","favorites","inquiries","addToCart","orders","revenueCad","returns","testPriceCad","advertisingSpendCad"].map(k=><input key={k} type="number" min="0" placeholder={k} value={r[k as keyof SalesTestRecord] as number ?? ""} onChange={e=>save(r,{[k]:Math.max(0,Number(e.target.value)||0)})}/>)}</div><p>CTR {m.ctr.toFixed(1)}% · 转化 {m.conversionRate.toFixed(1)}% · {salesDiagnosis(r)}</p><textarea placeholder="客户反馈与备注" value={r.notes??""} onChange={e=>save(r,{notes:e.target.value})}/><ConfirmDelete onConfirm={()=>dispatch({type:"deleteSalesTestRecord",id:r.id})}/></article>})}</section>; }
function ProductionSection({ product, update }: { product: ProductOpportunity; update: (patch: Partial<ProductOpportunity>) => void }) {
  if (!product.productionStatus) return null;
  const stages = ["queued", "prototyping", "prototype-complete", "test-selling", "selling"] as const;
  const labels = { queued: "打印队列", prototyping: "打样中", "prototype-complete": "样品完成", "test-selling": "测试销售", selling: "正式销售", unprinted: "未打印", paused: "已暂停" };
  const index = stages.indexOf(product.productionStatus as typeof stages[number]);
  const next = index >= 0 && index < stages.length - 1 ? stages[index + 1] : undefined;
  return <section className="panel"><h2>生产流程</h2><p>当前阶段：{labels[product.productionStatus]}</p>{product.radarProvenance && <div className="backup-note"><strong>来源：趋势雷达</strong><p>原始标题：{product.radarProvenance.title}</p><p>平台：{product.radarProvenance.platforms.join("、")} · 首次发现：{product.radarProvenance.firstSeenAt}</p>{product.radarProvenance.sourceLinks.map(link => <a key={link} href={link} target="_blank" rel="noreferrer">查看来源</a>)}</div>}<div className="button-row">{next && <button className="button primary" onClick={() => update({ productionStatus: next })}>推进到：{labels[next]}</button>}<button className="button ghost" onClick={() => update({ productionStatus: "paused" })}>暂停</button></div></section>;
}
export function ProductDetailPage() { const { productId }=useParams(); const {data,dispatch,setNotice}=useWorkbench(); const product=data.productOpportunities?.find(p=>p.id===productId); if(!product) return <><PageHeader title="产品不存在" description="该产品可能已被删除。"/><Link className="button ghost" to="/product-radar">返回雷达</Link></>; const licenses=(data.licenseRecords??[]).filter(r=>r.productId===product.id), prints=(data.productTestRecords??[]).filter(r=>r.productId===product.id), sales=(data.salesTestRecords??[]).filter(r=>r.productId===product.id), sources=(data.marketSources??[]).filter(r=>r.productId===product.id), evidence=evidenceInfo(sources); const update=(patch:Partial<ProductOpportunity>)=>dispatch({type:"upsertProductOpportunity",product:{...product,...patch}}); const move=(status:ProductStatus)=>{const result=transitionProduct(product,status,data.productTestRecords??[],data.salesTestRecords??[],data.licenseRecords??[]);if(!result.ok){setNotice(result.message);return;}update({status,statusHistory:[...(product.statusHistory??[]),{status,changedAt:new Date().toISOString()}]});}; return <><PageHeader title={product.name} description={`证据 ${evidence.count} 条，可信度 ${evidence.score}${evidence.stale?`，${evidence.stale} 条已过期`:""}`} /><StageActions product={product} onMove={move}/><ProductionSection product={product} update={update}/><ProductVisualComparison product={product} images={data.workshopImages ?? []} modelThumbnail={(data.workshopImages ?? []).find(image => image.id === (data.modelAssets ?? []).find(asset => asset.id === product.modelAssetId)?.thumbnailImageId)} onChange={update} onAddImage={(image) => dispatch({ type:"addWorkshopImage", image })}/><section className="editor-layout wide-editor"><div><Overview product={product} update={update}/><LicenseSection product={product} records={licenses}/></div><div><p className="error-text">批准仍缺：{approvalMissing(product,prints,sales,licenses).join("、")||"无"}</p><PrintTests product={product} records={prints}/><SalesTests product={product} records={sales}/></div></section></>; }
