import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "../components/ui/PageHeader";

type TrendItem = { id: string; title: string; imageUrl?: string; sources: Array<{ platform: string; url: string }>; category?: string; keywords: string[]; heatScore: number; competitionScore: number; printabilityScore: number; profitScore: number; totalScore: number; recommendation: "recommended" | "watch" | "skip"; status: "new" | "saved" | "preparing" | "converted" | "ignored"; estimatedPriceMin?: number; estimatedPriceMax?: number; estimatedProfitMin?: number; estimatedProfitMax?: number; ipRisk: string; matchedModelAssetIds: string[]; firstSeenAt: string; };
type RadarState = { items: TrendItem[]; settings: { keywords: string[]; enabledSources: Record<string, boolean> }; sources: Array<{ source: string; ok: boolean; error?: string; count?: number; checkedAt?: string }>; lastSuccessfulSearchAt?: string | null; searchLog: Array<{ query: string; at: string }> };
const labels = { recommended: "推荐", watch: "观察", skip: "跳过", new: "新发现", saved: "已保存", preparing: "准备中", converted: "已转生产", ignored: "已忽略" };

export function TrendRadarPage() {
  const [state, setState] = useState<RadarState>(); const [query, setQuery] = useState(""); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState("all"); const [message, setMessage] = useState("正在连接本地趋势雷达服务…");
  const load = async () => { try { const response = await fetch("/api/trend-radar/results"); const next = await response.json(); if (!next.ok) throw new Error(next.error); setState(next); setQuery(next.settings.keywords?.join("、") ?? ""); setMessage("本地趋势雷达已就绪。数据仅来自已配置的合法公开来源。"); } catch { setMessage("未连接本地服务。请使用“本地工作台”启动方式运行趋势雷达。"); } };
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => (state?.items ?? []).filter((item) => (!keyword || `${item.title} ${item.keywords.join(" ")}`.includes(keyword)) && (status === "all" || item.status === status)), [state, keyword, status]);
  const search = async () => { setMessage("正在执行本地搜索…"); const response = await fetch("/api/trend-radar/search", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query }) }); const next = await response.json(); if (next.ok) { setState(next); setMessage("搜索完成。来源错误不会阻断其他来源。 "); } else setMessage(next.error ?? "搜索失败"); };
  const changeStatus = async (id: string, nextStatus: string) => { const response = await fetch(`/api/trend-radar/items/${id}/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus }) }); if (response.ok) void load(); };
  return <><PageHeader title="趋势产品雷达" description="从已配置的合法公开数据源发现适合 3D 打印的趋势产品；不代表实时市场数据。" /><section className="panel"><div className="form-grid"><label>搜索关键词<input value={query} onChange={e => setQuery(e.target.value)} placeholder="例如：桌面收纳、礼品" /></label><button className="button primary" onClick={search}>立即搜索</button></div><p className="muted">{message}</p><span>上次更新：{state?.lastSuccessfulSearchAt ?? "尚未搜索"}　已启用来源：{Object.values(state?.settings.enabledSources ?? {}).filter(Boolean).length}　推荐项目：{(state?.items ?? []).filter(item => item.recommendation === "recommended").length}</span></section><section className="editor-layout wide-editor"><section className="panel"><h2>筛选与排序</h2><label>关键词<input value={keyword} onChange={e => setKeyword(e.target.value)} /></label><label>状态<select value={status} onChange={e => setStatus(e.target.value)}><option value="all">全部</option>{Object.entries(labels).slice(3).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></section><section className="panel"><h2>来源状态</h2>{(state?.sources ?? []).length ? state!.sources.map(source => <p key={source.source}>{source.source}：{source.ok ? `成功（${source.count ?? 0} 项）` : `不可用：${source.error}`}</p>) : <p className="muted">尚未执行搜索。来源必须配置合法公开 API 或数据源后才会返回结果。</p>}</section></section><section className="radar-product-list">{shown.length ? shown.map(item => <article className="radar-product" key={item.id}>{item.imageUrl && <img src={item.imageUrl} alt={item.title} />}<div className="card-top"><strong>{item.title}</strong><span className="badge">{labels[item.recommendation]}</span></div><p>来源：{item.sources.map(source => source.platform).join("、")} · 首次发现：{item.firstSeenAt.slice(0, 10)}</p><div className="radar-metrics"><span>热度 {item.heatScore}</span><span>竞争 {item.competitionScore}</span><span>可打印性 {item.printabilityScore}</span><span>利润 {item.profitScore}</span></div><p>IP 风险：{item.ipRisk} · 本地模型匹配：{item.matchedModelAssetIds.length} 个</p><div className="button-row"><button className="button ghost" onClick={() => changeStatus(item.id, "saved")}>保存</button><button className="button ghost" onClick={() => changeStatus(item.id, "ignored")}>忽略</button><button className="button primary" onClick={() => changeStatus(item.id, "preparing")}>加入生产准备</button></div></article>) : <section className="panel"><h2>暂无趋势项目</h2><p>请在本地服务配置已授权的公开数据源后点击“立即搜索”。系统不会绕过登录、验证码、限流或反爬措施。</p></section>}</section></>;
}
