import { useEffect, useState } from "react";
import { PageHeader } from "../components/ui/PageHeader";

type RawItem = { title: string; url: string; imageUrl?: string; priceText?: string; source: string; category?: string; keywords?: string[] };
type Capture = { id: string; items: RawItem[]; warnings: string[] };
type Trend = { id: string; title: string; status: string; recommendation: string; sources: Array<{ platform: string; url: string }>; firstSeenAt: string; };

export function TrendRadarPage() {
  const [url, setUrl] = useState(""); const [capture, setCapture] = useState<Capture>(); const [selected, setSelected] = useState<Set<number>>(new Set()); const [edits, setEdits] = useState<Record<number, Partial<RawItem>>>({}); const [message, setMessage] = useState("浏览器未启动"); const [importing, setImporting] = useState(false); const [items, setItems] = useState<Trend[]>([]);
  const load = async () => { try { const result = await (await fetch("/api/trend-radar/results")).json(); setItems(result.items ?? []); } catch { /* local server unavailable */ } };
  useEffect(() => { void load(); }, []);
  const call = async (path: string, body?: unknown, method = "POST") => { const response = await fetch(path, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const result = await response.json(); if (!result.ok) throw new Error(result.error); return result; };
  const open = async () => { try { await call("/api/browser/launch"); const result = await call("/api/browser/open", { url }); setMessage(result.status); } catch (error) { setMessage(error instanceof Error ? error.message : "打开失败"); } };
  const capturePage = async (scroll = false) => { try { const result = await call(scroll ? "/api/browser/scroll-capture" : "/api/browser/capture", scroll ? { maxScrolls: 5, scrollDelayMs: 1500, maxItems: 100 } : {}); const preview = await call(`/api/browser/captures/${result.captureId}`, undefined, "GET"); setCapture(preview.capture); setSelected(new Set(preview.capture.items.map((_: RawItem, index: number) => index))); setMessage("抓取完成，等待确认"); } catch (error) { setMessage(error instanceof Error ? error.message : "抓取失败"); } };
  const cancel = async () => { if (capture) await call(`/api/browser/captures/${capture.id}`, undefined, "DELETE"); setCapture(undefined); setSelected(new Set()); setMessage("已取消本次抓取"); };
  const confirm = async () => { if (!capture) return; setImporting(true); try { const result = await call(`/api/browser/captures/${capture.id}/import`, { selectedIndexes: [...selected], edits }); setMessage(result.errors?.length ? `部分项目导入失败；成功导入 ${result.imported} 条，跳过 ${result.skipped} 条。` : `成功导入 ${result.imported} 条，跳过 ${result.skipped} 条重复项目。`); if (!result.errors?.length) setCapture(undefined); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "导入失败，预览数据已保留"); } finally { setImporting(false); } };
  return <><PageHeader title="趋势产品雷达" description="在可见浏览器中手动浏览市场页面，抓取当前已加载内容并确认后导入。" /><section className="panel"><h2>网页抓取</h2><p className="muted">系统不会绕过登录、验证码、限流或网站访问限制。请先打开网页并自行完成必要操作。</p><div className="form-grid"><label>网页地址<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://…" /></label></div><div className="button-row"><button className="button primary" onClick={open}>启动并打开网页</button><button className="button ghost" onClick={() => capturePage()}>抓取当前页</button><button className="button ghost" onClick={() => capturePage(true)}>滚动抓取</button></div><p>{message}</p></section>{capture && <section className="panel"><h2>抓取预览</h2><p>{capture.warnings.join("；")}</p><div className="button-row"><button className="button ghost" onClick={() => setSelected(new Set(capture.items.map((_, i) => i)))}>全选</button><button className="button ghost" onClick={() => setSelected(new Set())}>取消全选</button><button className="button danger" onClick={cancel}>取消抓取</button><button className="button primary" disabled={importing || selected.size === 0} onClick={confirm}>{importing ? "正在导入" : `确认导入（已选择 ${selected.size}/${capture.items.length} 条）`}</button></div><div className="item-list">{capture.items.map((item, index) => { const edit = edits[index] ?? {}; const current = { ...item, ...edit }; const errors = !current.title ? ["缺少标题"] : !/^https?:\/\//.test(current.url) ? ["商品链接无效"] : []; return <article className="list-card" key={`${item.url}-${index}`}><label><input type="checkbox" checked={selected.has(index)} onChange={e => setSelected(value => { const next = new Set(value); e.target.checked ? next.add(index) : next.delete(index); return next; })} />选择</label>{current.imageUrl && <img src={current.imageUrl} alt="" style={{ maxWidth: 100 }} />}<input value={current.title} onChange={e => setEdits(value => ({ ...value, [index]: { ...value[index], title: e.target.value } }))} /><input placeholder="分类" value={current.category ?? ""} onChange={e => setEdits(value => ({ ...value, [index]: { ...value[index], category: e.target.value } }))} /><span>{current.priceText ?? "暂无数据"} · {current.source}</span><a href={current.url} target="_blank" rel="noreferrer">打开来源</a>{errors.map(error => <p className="error-text" key={error}>{error}</p>)}</article>})}</div></section>}<section className="panel"><h2>已导入趋势项目</h2>{items.length ? <div className="item-list">{items.map(item => <article className="list-card" key={item.id}><strong>{item.title}</strong><span>{item.recommendation} · {item.status}</span><a href={item.sources[0]?.url} target="_blank" rel="noreferrer">来源链接</a></article>)}</div> : <p className="muted">暂无已导入项目。</p>}</section></>;
}
